### ISSUE TITLE
"ArgumentException: Value does not fall within the expected range" when capture window

### ISSUE THREAD

**Issue by EurekaChen** [dme-compunet/ScreenCapture#1]
when
`var screenshot = screenCapture.CaptureWindow(windowHandler);`
then
`BitmapSource bitmap = Imaging.CreateBitmapSourceFromHBitmap(hBitmap, default, rect, BitmapSizeOptions.FromEmptyOptions()); `
will get error：
”ArgumentException: Value does not fall within the expected range."

**Comment by dme-compunet** [comment]
Thanks, it happens because the rectangle has negative values, I'll fix it soon.
